pub const KEYWORDS: &[&str] = &[
    "And",
    "As",
    "ByRef",
    "ByVal",
    "Call",
    "Case",
    "Const",
    "Declare",
    "Dim",
    "Do",
    "Each",
    "Else",
    "ElseIf",
    "End",
    "Enum",
    "Erase",
    "Error",
    "Event",
    "Exit",
    "For",
    "Friend",
    "Function",
    "Get",
    "GoSub",
    "GoTo",
    "If",
    "Implements",
    "In",
    "Is",
    "Let",
    "Lib",
    "Like",
    "Loop",
    "Me",
    "Mod",
    "New",
    "Next",
    "Not",
    "Nothing",
    "Null",
    "On",
    "Option",
    "Optional",
    "Or",
    "ParamArray",
    "Preserve",
    "Private",
    "Property",
    "Public",
    "RaiseEvent",
    "ReDim",
    "Rem",
    "Resume",
    "Return",
    "Select",
    "Set",
    "Static",
    "Step",
    "Stop",
    "Sub",
    "Then",
    "To",
    "Type",
    "TypeOf",
    "Until",
    "Wend",
    "While",
    "With",
    "WithEvents",
    "Xor",
];

pub const BUILTIN_FUNCTIONS: &[&str] = &[
    "Abs",
    "Array",
    "Asc",
    "CBool",
    "CByte",
    "CCur",
    "CDate",
    "CDbl",
    "CDec",
    "Chr",
    "CInt",
    "CLng",
    "CLngLng",
    "CLngPtr",
    "CSng",
    "CStr",
    "CVar",
    "DateAdd",
    "DateDiff",
    "DatePart",
    "DateSerial",
    "DateValue",
    "Day",
    "Dir",
    "Environ",
    "EOF",
    "Format",
    "FreeFile",
    "Hex",
    "Hour",
    "IIf",
    "InStr",
    "InStrRev",
    "InputBox",
    "Int",
    "IsArray",
    "IsDate",
    "IsEmpty",
    "IsError",
    "IsMissing",
    "IsNull",
    "IsNumeric",
    "IsObject",
    "Join",
    "LBound",
    "LCase",
    "Left",
    "Len",
    "Log",
    "LTrim",
    "Mid",
    "Minute",
    "Month",
    "MonthName",
    "MsgBox",
    "Now",
    "Oct",
    "Replace",
    "RGB",
    "Right",
    "Rnd",
    "Round",
    "RTrim",
    "Second",
    "Sgn",
    "Shell",
    "Space",
    "Split",
    "Sqr",
    "Str",
    "StrComp",
    "StrConv",
    "String",
    "Timer",
    "TimeSerial",
    "TimeValue",
    "Trim",
    "TypeName",
    "UBound",
    "UCase",
    "Val",
    "VarType",
    "Weekday",
    "WeekdayName",
    "Year",
];

pub struct BuiltinSignature {
    pub name: &'static str,
    /// (param_name, param_type, is_optional)
    pub params: &'static [(&'static str, &'static str, bool)],
    pub return_type: Option<&'static str>,
}

pub const BUILTIN_SIGNATURES: &[BuiltinSignature] = &[
    BuiltinSignature {
        name: "MsgBox",
        params: &[
            ("Prompt", "String", false),
            ("Buttons", "VbMsgBoxStyle", true),
            ("Title", "String", true),
            ("HelpFile", "String", true),
            ("Context", "Long", true),
        ],
        return_type: Some("VbMsgBoxResult"),
    },
    BuiltinSignature {
        name: "InputBox",
        params: &[
            ("Prompt", "String", false),
            ("Title", "String", true),
            ("Default", "String", true),
            ("XPos", "Long", true),
            ("YPos", "Long", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "InStr",
        params: &[
            ("Start", "Long", true),
            ("String1", "String", false),
            ("String2", "String", false),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "InStrRev",
        params: &[
            ("StringCheck", "String", false),
            ("StringMatch", "String", false),
            ("Start", "Long", true),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "Left",
        params: &[("String", "String", false), ("Length", "Long", false)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Right",
        params: &[("String", "String", false), ("Length", "Long", false)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Mid",
        params: &[
            ("String", "String", false),
            ("Start", "Long", false),
            ("Length", "Long", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Len",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "Format",
        params: &[("Expression", "Variant", false), ("Format", "String", true)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Replace",
        params: &[
            ("Expression", "String", false),
            ("Find", "String", false),
            ("Replace", "String", false),
            ("Start", "Long", true),
            ("Count", "Long", true),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Split",
        params: &[
            ("Expression", "String", false),
            ("Delimiter", "String", true),
            ("Limit", "Long", true),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("String()"),
    },
    BuiltinSignature {
        name: "Join",
        params: &[
            ("SourceArray", "Variant", false),
            ("Delimiter", "String", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "UBound",
        params: &[("Array", "Variant", false), ("Dimension", "Long", true)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "LBound",
        params: &[("Array", "Variant", false), ("Dimension", "Long", true)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "CStr",
        params: &[("Expression", "Variant", false)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "CInt",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Integer"),
    },
    BuiltinSignature {
        name: "CLng",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "CDbl",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Double"),
    },
    BuiltinSignature {
        name: "IIf",
        params: &[
            ("Expression", "Boolean", false),
            ("TruePart", "Variant", false),
            ("FalsePart", "Variant", false),
        ],
        return_type: Some("Variant"),
    },
    BuiltinSignature {
        name: "IsNull",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Boolean"),
    },
    BuiltinSignature {
        name: "IsEmpty",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Boolean"),
    },
];

pub const BUILTIN_TYPES: &[&str] = &[
    "Boolean", "Byte", "Integer", "Long", "LongLong", "LongPtr", "Single", "Double", "Currency",
    "Date", "String", "Variant", "Object",
];
