pub const KEYWORDS: &[&str] = &[
    "And",
    "Append",
    "As",
    "Binary",
    "ByRef",
    "ByVal",
    "Call",
    "Case",
    "Close",
    "Const",
    "Declare",
    "Dim",
    "Do",
    "Each",
    "Else",
    "ElseIf",
    "End",
    "Enum",
    "Erase",
    "Error",
    "Event",
    "Exit",
    "For",
    "Friend",
    "Function",
    "Get",
    "GoSub",
    "GoTo",
    "If",
    "Implements",
    "In",
    "Input",
    "Is",
    "Let",
    "Lib",
    "Like",
    "Lock",
    "Loop",
    "Me",
    "Mod",
    "New",
    "Next",
    "Not",
    "Nothing",
    "Null",
    "On",
    "Open",
    "Option",
    "Optional",
    "Or",
    "Output",
    "ParamArray",
    "Preserve",
    "Print",
    "Private",
    "Property",
    "Public",
    "Put",
    "RaiseEvent",
    "Random",
    "Read",
    "ReDim",
    "Rem",
    "Resume",
    "Return",
    "Seek",
    "Select",
    "Set",
    "Static",
    "Step",
    "Stop",
    "Sub",
    "Then",
    "To",
    "Type",
    "TypeOf",
    "Unlock",
    "Until",
    "Wend",
    "While",
    "With",
    "WithEvents",
    "Write",
    "Xor",
];

pub const BUILTIN_FUNCTIONS: &[&str] = &[
    "Abs",
    "Array",
    "Asc",
    "Atn",
    "CBool",
    "CByte",
    "CCur",
    "CDate",
    "CDbl",
    "CDec",
    "ChDir",
    "ChDrive",
    "Chr",
    "CInt",
    "CLng",
    "CLngLng",
    "CLngPtr",
    "Cos",
    "CreateObject",
    "CSng",
    "CStr",
    "CurDir",
    "CVar",
    "DateAdd",
    "DateDiff",
    "DatePart",
    "DateSerial",
    "DateValue",
    "Day",
    "Dir",
    "DoEvents",
    "Environ",
    "EOF",
    "Exp",
    "FileCopy",
    "FileDateTime",
    "FileLen",
    "Fix",
    "Format",
    "FreeFile",
    "GetAttr",
    "GetObject",
    "Hex",
    "Hour",
    "IIf",
    "InStr",
    "InStrRev",
    "InputBox",
    "Int",
    "IsArray",
    "IsDate",
    "IsEmpty",
    "IsError",
    "IsMissing",
    "IsNull",
    "IsNumeric",
    "IsObject",
    "Join",
    "Kill",
    "LBound",
    "LCase",
    "Left",
    "Len",
    "Loc",
    "LOF",
    "Log",
    "LTrim",
    "Mid",
    "Minute",
    "MkDir",
    "Month",
    "MonthName",
    "MsgBox",
    "Now",
    "Oct",
    "Replace",
    "RGB",
    "Right",
    "RmDir",
    "Rnd",
    "Round",
    "RTrim",
    "Second",
    "SetAttr",
    "Sgn",
    "Shell",
    "Sin",
    "Space",
    "Split",
    "Sqr",
    "Str",
    "StrComp",
    "StrConv",
    "String",
    "Tan",
    "Timer",
    "TimeSerial",
    "TimeValue",
    "Trim",
    "TypeName",
    "UBound",
    "UCase",
    "Val",
    "VarType",
    "Weekday",
    "WeekdayName",
    "Year",
];

pub struct BuiltinSignature {
    pub name: &'static str,
    /// (param_name, param_type, is_optional)
    pub params: &'static [(&'static str, &'static str, bool)],
    pub return_type: Option<&'static str>,
}

pub const BUILTIN_SIGNATURES: &[BuiltinSignature] = &[
    BuiltinSignature {
        name: "MsgBox",
        params: &[
            ("Prompt", "String", false),
            ("Buttons", "VbMsgBoxStyle", true),
            ("Title", "String", true),
            ("HelpFile", "String", true),
            ("Context", "Long", true),
        ],
        return_type: Some("VbMsgBoxResult"),
    },
    BuiltinSignature {
        name: "InputBox",
        params: &[
            ("Prompt", "String", false),
            ("Title", "String", true),
            ("Default", "String", true),
            ("XPos", "Long", true),
            ("YPos", "Long", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "InStr",
        params: &[
            ("Start", "Long", true),
            ("String1", "String", false),
            ("String2", "String", false),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "InStrRev",
        params: &[
            ("StringCheck", "String", false),
            ("StringMatch", "String", false),
            ("Start", "Long", true),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "Left",
        params: &[("String", "String", false), ("Length", "Long", false)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Right",
        params: &[("String", "String", false), ("Length", "Long", false)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Mid",
        params: &[
            ("String", "String", false),
            ("Start", "Long", false),
            ("Length", "Long", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Len",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "Format",
        params: &[("Expression", "Variant", false), ("Format", "String", true)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Replace",
        params: &[
            ("Expression", "String", false),
            ("Find", "String", false),
            ("Replace", "String", false),
            ("Start", "Long", true),
            ("Count", "Long", true),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Split",
        params: &[
            ("Expression", "String", false),
            ("Delimiter", "String", true),
            ("Limit", "Long", true),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("String()"),
    },
    BuiltinSignature {
        name: "Join",
        params: &[
            ("SourceArray", "Variant", false),
            ("Delimiter", "String", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "UBound",
        params: &[("Array", "Variant", false), ("Dimension", "Long", true)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "LBound",
        params: &[("Array", "Variant", false), ("Dimension", "Long", true)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "CStr",
        params: &[("Expression", "Variant", false)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "CInt",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Integer"),
    },
    BuiltinSignature {
        name: "CLng",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "CDbl",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Double"),
    },
    BuiltinSignature {
        name: "IIf",
        params: &[
            ("Expression", "Boolean", false),
            ("TruePart", "Variant", false),
            ("FalsePart", "Variant", false),
        ],
        return_type: Some("Variant"),
    },
    BuiltinSignature {
        name: "IsNull",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Boolean"),
    },
    BuiltinSignature {
        name: "IsEmpty",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Boolean"),
    },
];

pub const BUILTIN_TYPES: &[&str] = &[
    "Boolean", "Byte", "Integer", "Long", "LongLong", "LongPtr", "Single", "Double", "Currency",
    "Date", "String", "Variant", "Object",
];

/// VBA intrinsic constants (vbCrLf, vbYesNo, etc.) that are always available.
pub const VBA_CONSTANTS: &[&str] = &[
    // String constants
    "vbBack",
    "vbCr",
    "vbCrLf",
    "vbFormFeed",
    "vbLf",
    "vbNewLine",
    "vbNullChar",
    "vbNullString",
    "vbTab",
    "vbVerticalTab",
    // MsgBox button constants
    "vbAbortRetryIgnore",
    "vbOKCancel",
    "vbOKOnly",
    "vbRetryCancel",
    "vbYesNo",
    "vbYesNoCancel",
    // MsgBox icon constants
    "vbCritical",
    "vbExclamation",
    "vbInformation",
    "vbQuestion",
    // MsgBox default button constants
    "vbDefaultButton1",
    "vbDefaultButton2",
    "vbDefaultButton3",
    "vbDefaultButton4",
    // MsgBox return values
    "vbAbort",
    "vbCancel",
    "vbIgnore",
    "vbNo",
    "vbOK",
    "vbRetry",
    "vbYes",
    // MsgBox modality
    "vbApplicationModal",
    "vbSystemModal",
    // Tristate
    "vbFalse",
    "vbTrue",
    "vbUseDefault",
    // VarType constants
    "vbArray",
    "vbBoolean",
    "vbByte",
    "vbCurrency",
    "vbDataObject",
    "vbDate",
    "vbDecimal",
    "vbDouble",
    "vbEmpty",
    "vbError",
    "vbInteger",
    "vbLong",
    "vbLongLong",
    "vbNull",
    "vbObject",
    "vbSingle",
    "vbString",
    "vbUserDefinedType",
    "vbVariant",
    // Miscellaneous
    "vbBinaryCompare",
    "vbDatabaseCompare",
    "vbObjectError",
    "vbTextCompare",
];

/// Common Excel enum constants used in VBA macros.
pub const EXCEL_CONSTANTS: &[&str] = &[
    // XlDirection
    "xlDown",
    "xlToLeft",
    "xlToRight",
    "xlUp",
    // XlBordersIndex
    "xlDiagonalDown",
    "xlDiagonalUp",
    "xlEdgeBottom",
    "xlEdgeLeft",
    "xlEdgeRight",
    "xlEdgeTop",
    "xlInsideHorizontal",
    "xlInsideVertical",
    // XlBorderWeight
    "xlHairline",
    "xlMedium",
    "xlThick",
    "xlThin",
    // XlLineStyle
    "xlContinuous",
    "xlDash",
    "xlDashDot",
    "xlDashDotDot",
    "xlDot",
    "xlDouble",
    "xlLineStyleNone",
    "xlSlantDashDot",
    // XlHAlign
    "xlHAlignCenter",
    "xlHAlignLeft",
    "xlHAlignRight",
    "xlHAlignGeneral",
    // XlVAlign
    "xlVAlignBottom",
    "xlVAlignCenter",
    "xlVAlignTop",
    // XlCalculation
    "xlCalculationAutomatic",
    "xlCalculationManual",
    "xlCalculationSemiautomatic",
    // XlCellType
    "xlCellTypeBlanks",
    "xlCellTypeConstants",
    "xlCellTypeFormulas",
    "xlCellTypeLastCell",
    "xlCellTypeVisible",
    // XlDeleteShiftDirection / XlInsertShiftDirection
    "xlShiftDown",
    "xlShiftToLeft",
    "xlShiftToRight",
    "xlShiftUp",
    // XlSortOrder
    "xlAscending",
    "xlDescending",
    // XlYesNoGuess
    "xlGuess",
    "xlNo",
    "xlYes",
    // XlLookAt
    "xlPart",
    "xlWhole",
    // XlSearchOrder
    "xlByColumns",
    "xlByRows",
    // XlCopyPictureFormat
    "xlBitmap",
    "xlPicture",
    // XlPasteType
    "xlPasteAll",
    "xlPasteFormats",
    "xlPasteValues",
    "xlPasteFormulas",
    // XlSheetVisibility
    "xlSheetHidden",
    "xlSheetVeryHidden",
    "xlSheetVisible",
    // XlAutoFillType
    "xlFillDefault",
    "xlFillSeries",
    // Common misc
    "xlNone",
    "xlAutomatic",
    "xlManual",
    "xlGeneral",
];
