pub const KEYWORDS: &[&str] = &[
    "And",
    "Append",
    "As",
    "Binary",
    "ByRef",
    "ByVal",
    "Call",
    "Case",
    "Close",
    "Const",
    "Declare",
    "Dim",
    "Do",
    "Each",
    "Else",
    "ElseIf",
    "End",
    "Enum",
    "Erase",
    "Error",
    "Event",
    "Exit",
    "For",
    "Friend",
    "Function",
    "Get",
    "GoSub",
    "GoTo",
    "If",
    "Implements",
    "In",
    "Input",
    "Is",
    "Let",
    "Lib",
    "Like",
    "Lock",
    "Loop",
    "Me",
    "Mod",
    "New",
    "Next",
    "Not",
    "Nothing",
    "Null",
    "On",
    "Open",
    "Option",
    "Optional",
    "Or",
    "Output",
    "ParamArray",
    "Preserve",
    "Print",
    "Private",
    "Property",
    "Public",
    "Put",
    "RaiseEvent",
    "Random",
    "Read",
    "ReDim",
    "Rem",
    "Resume",
    "Return",
    "Seek",
    "Select",
    "Set",
    "Static",
    "Step",
    "Stop",
    "Sub",
    "Then",
    "To",
    "Type",
    "TypeOf",
    "Unlock",
    "Until",
    "Wend",
    "While",
    "With",
    "WithEvents",
    "Write",
    "Xor",
];

pub const BUILTIN_FUNCTIONS: &[&str] = &[
    "Abs",
    "Array",
    "Asc",
    "Atn",
    "CBool",
    "CByte",
    "CCur",
    "CDate",
    "CDbl",
    "CDec",
    "ChDir",
    "ChDrive",
    "Chr",
    "CInt",
    "CLng",
    "CLngLng",
    "CLngPtr",
    "Cos",
    "CreateObject",
    "CSng",
    "CStr",
    "CurDir",
    "CVar",
    "CVErr",
    "DateAdd",
    "DateDiff",
    "DatePart",
    "DateSerial",
    "DateValue",
    "Day",
    "Dir",
    "DoEvents",
    "Environ",
    "EOF",
    "Exp",
    "FileCopy",
    "FileDateTime",
    "FileLen",
    "Fix",
    "Format",
    "FormatDateTime",
    "FreeFile",
    "GetAttr",
    "GetObject",
    "Hex",
    "Hour",
    "IIf",
    "InStr",
    "InStrRev",
    "InputBox",
    "Int",
    "IsArray",
    "IsDate",
    "IsEmpty",
    "IsError",
    "IsMissing",
    "IsNull",
    "IsNumeric",
    "IsObject",
    "Join",
    "Kill",
    "LBound",
    "LCase",
    "Left",
    "Len",
    "Loc",
    "LOF",
    "Log",
    "LTrim",
    "Mid",
    "Minute",
    "MkDir",
    "Month",
    "MonthName",
    "MsgBox",
    "Now",
    "Oct",
    "Replace",
    "RGB",
    "Right",
    "RmDir",
    "Rnd",
    "Round",
    "RTrim",
    "Second",
    "SetAttr",
    "Sgn",
    "Shell",
    "Sin",
    "Space",
    "Split",
    "Sqr",
    "Str",
    "StrComp",
    "StrConv",
    "String",
    "Tan",
    "Timer",
    "TimeSerial",
    "TimeValue",
    "Trim",
    "TypeName",
    "UBound",
    "UCase",
    "Val",
    "VarType",
    "Weekday",
    "WeekdayName",
    "Year",
];

pub struct BuiltinSignature {
    pub name: &'static str,
    /// (param_name, param_type, is_optional)
    pub params: &'static [(&'static str, &'static str, bool)],
    pub return_type: Option<&'static str>,
}

pub const BUILTIN_SIGNATURES: &[BuiltinSignature] = &[
    BuiltinSignature {
        name: "MsgBox",
        params: &[
            ("Prompt", "String", false),
            ("Buttons", "VbMsgBoxStyle", true),
            ("Title", "String", true),
            ("HelpFile", "String", true),
            ("Context", "Long", true),
        ],
        return_type: Some("VbMsgBoxResult"),
    },
    BuiltinSignature {
        name: "InputBox",
        params: &[
            ("Prompt", "String", false),
            ("Title", "String", true),
            ("Default", "String", true),
            ("XPos", "Long", true),
            ("YPos", "Long", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "InStr",
        params: &[
            ("Start", "Long", true),
            ("String1", "String", false),
            ("String2", "String", false),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "InStrRev",
        params: &[
            ("StringCheck", "String", false),
            ("StringMatch", "String", false),
            ("Start", "Long", true),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "Left",
        params: &[("String", "String", false), ("Length", "Long", false)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Right",
        params: &[("String", "String", false), ("Length", "Long", false)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Mid",
        params: &[
            ("String", "String", false),
            ("Start", "Long", false),
            ("Length", "Long", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Len",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "Format",
        params: &[("Expression", "Variant", false), ("Format", "String", true)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Replace",
        params: &[
            ("Expression", "String", false),
            ("Find", "String", false),
            ("Replace", "String", false),
            ("Start", "Long", true),
            ("Count", "Long", true),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "Split",
        params: &[
            ("Expression", "String", false),
            ("Delimiter", "String", true),
            ("Limit", "Long", true),
            ("Compare", "VbCompareMethod", true),
        ],
        return_type: Some("String()"),
    },
    BuiltinSignature {
        name: "Join",
        params: &[
            ("SourceArray", "Variant", false),
            ("Delimiter", "String", true),
        ],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "UBound",
        params: &[("Array", "Variant", false), ("Dimension", "Long", true)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "LBound",
        params: &[("Array", "Variant", false), ("Dimension", "Long", true)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "CStr",
        params: &[("Expression", "Variant", false)],
        return_type: Some("String"),
    },
    BuiltinSignature {
        name: "CInt",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Integer"),
    },
    BuiltinSignature {
        name: "CLng",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Long"),
    },
    BuiltinSignature {
        name: "CDbl",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Double"),
    },
    BuiltinSignature {
        name: "IIf",
        params: &[
            ("Expression", "Boolean", false),
            ("TruePart", "Variant", false),
            ("FalsePart", "Variant", false),
        ],
        return_type: Some("Variant"),
    },
    BuiltinSignature {
        name: "IsNull",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Boolean"),
    },
    BuiltinSignature {
        name: "IsEmpty",
        params: &[("Expression", "Variant", false)],
        return_type: Some("Boolean"),
    },
];

pub const BUILTIN_TYPES: &[&str] = &[
    "Boolean", "Byte", "Integer", "Long", "LongLong", "LongPtr", "Single", "Double", "Currency",
    "Date", "String", "Variant", "Object",
];

/// VBA intrinsic constants (vbCrLf, vbYesNo, etc.) that are always available.
pub const VBA_CONSTANTS: &[&str] = &[
    // String constants
    "vbBack",
    "vbCr",
    "vbCrLf",
    "vbFormFeed",
    "vbLf",
    "vbNewLine",
    "vbNullChar",
    "vbNullString",
    "vbTab",
    "vbVerticalTab",
    // MsgBox button constants
    "vbAbortRetryIgnore",
    "vbOKCancel",
    "vbOKOnly",
    "vbRetryCancel",
    "vbYesNo",
    "vbYesNoCancel",
    // MsgBox icon constants
    "vbCritical",
    "vbExclamation",
    "vbInformation",
    "vbQuestion",
    // MsgBox default button constants
    "vbDefaultButton1",
    "vbDefaultButton2",
    "vbDefaultButton3",
    "vbDefaultButton4",
    // MsgBox return values
    "vbAbort",
    "vbCancel",
    "vbIgnore",
    "vbNo",
    "vbOK",
    "vbRetry",
    "vbYes",
    // MsgBox modality / style
    "vbApplicationModal",
    "vbMsgBoxHelpButton",
    "vbMsgBoxRight",
    "vbMsgBoxRtlReading",
    "vbMsgBoxSetForeground",
    "vbSystemModal",
    // Tristate
    "vbFalse",
    "vbTrue",
    "vbUseDefault",
    // VarType constants
    "vbArray",
    "vbBoolean",
    "vbByte",
    "vbCurrency",
    "vbDataObject",
    "vbDate",
    "vbDecimal",
    "vbDouble",
    "vbEmpty",
    "vbError",
    "vbInteger",
    "vbLong",
    "vbLongLong",
    "vbNull",
    "vbObject",
    "vbSingle",
    "vbString",
    "vbUserDefinedType",
    "vbVariant",
    // File attribute constants
    "vbAlias",
    "vbArchive",
    "vbDirectory",
    "vbHidden",
    "vbNormal",
    "vbReadOnly",
    "vbSystem",
    "vbVolume",
    // Color constants
    "vbBlack",
    "vbBlue",
    "vbCyan",
    "vbGreen",
    "vbMagenta",
    "vbRed",
    "vbWhite",
    "vbYellow",
    // Date format constants
    "vbGeneralDate",
    "vbLongDate",
    "vbLongTime",
    "vbShortDate",
    "vbShortTime",
    // StrConv constants
    "vbFromUnicode",
    "vbHiragana",
    "vbKatakana",
    "vbLowerCase",
    "vbNarrow",
    "vbProperCase",
    "vbUnicode",
    "vbUpperCase",
    "vbWide",
    // Miscellaneous
    "vbBinaryCompare",
    "vbDatabaseCompare",
    "vbObjectError",
    "vbTextCompare",
];

/// Common Excel enum constants used in VBA macros.
pub const EXCEL_CONSTANTS: &[&str] = &[
    // XlDirection
    "xlDown",
    "xlToLeft",
    "xlToRight",
    "xlUp",
    // XlBordersIndex
    "xlDiagonalDown",
    "xlDiagonalUp",
    "xlEdgeBottom",
    "xlEdgeLeft",
    "xlEdgeRight",
    "xlEdgeTop",
    "xlInsideHorizontal",
    "xlInsideVertical",
    // XlBorderWeight
    "xlHairline",
    "xlMedium",
    "xlThick",
    "xlThin",
    // XlLineStyle
    "xlContinuous",
    "xlDash",
    "xlDashDot",
    "xlDashDotDot",
    "xlDot",
    "xlDouble",
    "xlLineStyleNone",
    "xlSlantDashDot",
    // XlHAlign
    "xlHAlignCenter",
    "xlHAlignLeft",
    "xlHAlignRight",
    "xlHAlignGeneral",
    // XlVAlign
    "xlVAlignBottom",
    "xlVAlignCenter",
    "xlVAlignTop",
    // XlCalculation
    "xlCalculationAutomatic",
    "xlCalculationManual",
    "xlCalculationSemiautomatic",
    // XlCellType
    "xlCellTypeBlanks",
    "xlCellTypeConstants",
    "xlCellTypeFormulas",
    "xlCellTypeLastCell",
    "xlCellTypeVisible",
    // XlDeleteShiftDirection / XlInsertShiftDirection
    "xlShiftDown",
    "xlShiftToLeft",
    "xlShiftToRight",
    "xlShiftUp",
    // XlSortOrder
    "xlAscending",
    "xlDescending",
    // XlSortOrientation
    "xlSortColumns",
    "xlSortRows",
    "xlTopToBottom",
    // XlYesNoGuess
    "xlGuess",
    "xlNo",
    "xlYes",
    // XlLookAt
    "xlPart",
    "xlWhole",
    // XlSearchOrder
    "xlByColumns",
    "xlByRows",
    // XlCopyPictureFormat
    "xlBitmap",
    "xlPicture",
    // XlPasteType
    "xlPasteAll",
    "xlPasteFormats",
    "xlPasteValues",
    "xlPasteFormulas",
    // XlSheetVisibility
    "xlSheetHidden",
    "xlSheetVeryHidden",
    "xlSheetVisible",
    // XlAutoFillType
    "xlFillDefault",
    "xlFillSeries",
    // XlSortOn
    "xlSortOnCellColor",
    "xlSortOnFontColor",
    "xlSortOnIcon",
    "xlSortOnValues",
    // XlFindLookIn
    "xlComments",
    "xlFormulas",
    "xlValues",
    // XlSearchDirection
    "xlNext",
    "xlPrevious",
    // XlDVType (data validation)
    "xlValidateCustom",
    "xlValidateDate",
    "xlValidateDecimal",
    "xlValidateInputOnly",
    "xlValidateList",
    "xlValidateTextLength",
    "xlValidateTime",
    "xlValidateWholeNumber",
    // XlDVAlertStyle (data validation alert)
    "xlValidAlertInformation",
    "xlValidAlertStop",
    "xlValidAlertWarning",
    // XlFileFormat
    "xlAddIn",
    "xlAddIn8",
    "xlCSV",
    "xlCSVMac",
    "xlCSVMSDOS",
    "xlCSVUTF8",
    "xlCSVWindows",
    "xlCurrentPlatformText",
    "xlDBF2",
    "xlDBF3",
    "xlDBF4",
    "xlDIF",
    "xlExcel12",
    "xlExcel2",
    "xlExcel2FarEast",
    "xlExcel3",
    "xlExcel4",
    "xlExcel4Workbook",
    "xlExcel5",
    "xlExcel7",
    "xlExcel8",
    "xlExcel9795",
    "xlHtml",
    "xlIntlAddIn",
    "xlIntlMacro",
    "xlOpenDocumentSpreadsheet",
    "xlOpenXMLAddIn",
    "xlOpenXMLStrictWorkbook",
    "xlOpenXMLTemplate",
    "xlOpenXMLTemplateMacroEnabled",
    "xlOpenXMLWorkbook",
    "xlOpenXMLWorkbookMacroEnabled",
    "xlSYLK",
    "xlTemplate",
    "xlTemplate8",
    "xlTextMac",
    "xlTextMSDOS",
    "xlTextPrinter",
    "xlTextWindows",
    "xlUnicodeText",
    "xlWebArchive",
    "xlWorkbookDefault",
    "xlWorkbookNormal",
    "xlXMLSpreadsheet",
    // XlPivotTableSourceType
    "xlConsolidation",
    "xlDatabase",
    "xlExternal",
    "xlPivotTable",
    "xlScenario",
    // XlPivotFieldOrientation
    "xlColumnField",
    "xlDataField",
    "xlHidden",
    "xlPageField",
    "xlRowField",
    // XlConsolidationFunction
    "xlAverage",
    "xlCount",
    "xlCountNums",
    "xlMax",
    "xlMin",
    "xlProduct",
    "xlStDev",
    "xlStDevP",
    "xlSum",
    "xlVar",
    "xlVarP",
    // XlChartType
    "xl3DArea",
    "xl3DAreaStacked",
    "xl3DAreaStacked100",
    "xl3DBarClustered",
    "xl3DBarStacked",
    "xl3DBarStacked100",
    "xl3DColumn",
    "xl3DColumnClustered",
    "xl3DColumnStacked",
    "xl3DColumnStacked100",
    "xl3DLine",
    "xl3DPie",
    "xl3DPieExploded",
    "xlArea",
    "xlAreaStacked",
    "xlAreaStacked100",
    "xlBarClustered",
    "xlBarOfPie",
    "xlBarStacked",
    "xlBarStacked100",
    "xlBoxwhisker",
    "xlBubble",
    "xlBubble3DEffect",
    "xlColumnClustered",
    "xlColumnStacked",
    "xlColumnStacked100",
    "xlCombo",
    "xlComboAreaStackedColumnClustered",
    "xlComboColumnClusteredLine",
    "xlComboColumnClusteredLineSecondaryAxis",
    "xlConeBarClustered",
    "xlConeBarStacked",
    "xlConeBarStacked100",
    "xlConeCol",
    "xlConeColClustered",
    "xlConeColStacked",
    "xlConeColStacked100",
    "xlCylinderBarClustered",
    "xlCylinderBarStacked",
    "xlCylinderBarStacked100",
    "xlCylinderCol",
    "xlCylinderColClustered",
    "xlCylinderColStacked",
    "xlCylinderColStacked100",
    "xlDoughnut",
    "xlDoughnutExploded",
    "xlFunnel",
    "xlHistogram",
    "xlLine",
    "xlLineMarkers",
    "xlLineMarkersStacked",
    "xlLineMarkersStacked100",
    "xlLineStacked",
    "xlLineStacked100",
    "xlOtherCombinations",
    "xlPareto",
    "xlPie",
    "xlPieExploded",
    "xlPieOfPie",
    "xlPyramidBarClustered",
    "xlPyramidBarStacked",
    "xlPyramidBarStacked100",
    "xlPyramidCol",
    "xlPyramidColClustered",
    "xlPyramidColStacked",
    "xlPyramidColStacked100",
    "xlRadar",
    "xlRadarFilled",
    "xlRadarMarkers",
    "xlRegionMap",
    "xlStockHLC",
    "xlStockOHLC",
    "xlStockVHLC",
    "xlStockVOHLC",
    "xlSunburst",
    "xlSurface",
    "xlSurfaceTopView",
    "xlSurfaceTopViewWireframe",
    "xlSurfaceWireframe",
    "xlTreemap",
    "xlWaterfall",
    "xlXYScatter",
    "xlXYScatterLines",
    "xlXYScatterLinesNoMarkers",
    "xlXYScatterSmooth",
    "xlXYScatterSmoothNoMarkers",
    // XlAxisType
    "xlCategory",
    "xlSeriesAxis",
    "xlValue",
    // XlConnectionType
    "xlConnectionTypeODBC",
    "xlConnectionTypeOLEDB",
    "xlConnectionTypeXMLMAP",
    // CVError constants
    "xlErrDiv0",
    "xlErrNA",
    "xlErrName",
    "xlErrNull",
    "xlErrNum",
    "xlErrRef",
    "xlErrValue",
    // XlSheetType
    "xlChart",
    "xlDialogSheet",
    "xlExcel4IntlMacroSheet",
    "xlExcel4MacroSheet",
    "xlWorksheet",
    // XlPageOrientation
    "xlLandscape",
    "xlPortrait",
    // XlColorIndex
    "xlColorIndexAutomatic",
    "xlColorIndexNone",
    // XlAutoFilterOperator
    "xlAnd",
    "xlBottom10Items",
    "xlBottom10Percent",
    "xlFilterCellColor",
    "xlFilterDynamic",
    "xlFilterFontColor",
    "xlFilterIcon",
    "xlFilterValues",
    "xlOr",
    "xlTop10Items",
    "xlTop10Percent",
    // XlPasteSpecialOperation
    "xlPasteSpecialOperationAdd",
    "xlPasteSpecialOperationDivide",
    "xlPasteSpecialOperationMultiply",
    "xlPasteSpecialOperationNone",
    "xlPasteSpecialOperationSubtract",
    // XlSpecialCellsValue
    "xlErrors",
    "xlLogical",
    "xlNumbers",
    "xlTextValues",
    // XlWindowState
    "xlMaximized",
    "xlMinimized",
    "xlNormal",
    // XlReferenceStyle
    "xlA1",
    "xlR1C1",
    // XlPattern
    "xlPatternAutomatic",
    "xlPatternChecker",
    "xlPatternCrissCross",
    "xlPatternDown",
    "xlPatternGray16",
    "xlPatternGray25",
    "xlPatternGray50",
    "xlPatternGray75",
    "xlPatternGray8",
    "xlPatternGrid",
    "xlPatternHorizontal",
    "xlPatternLightDown",
    "xlPatternLightHorizontal",
    "xlPatternLightUp",
    "xlPatternLightVertical",
    "xlPatternNone",
    "xlPatternSemiGray75",
    "xlPatternSolid",
    "xlPatternUp",
    "xlPatternVertical",
    // XlRowCol
    "xlColumns",
    "xlRows",
    // XlEnableCancelKey
    "xlDisabled",
    "xlErrorHandler",
    "xlInterrupt",
    // Excel.Constants enum (miscellaneous constants used across Excel methods)
    "xl3DBar",
    "xl3DEffects1",
    "xl3DEffects2",
    "xl3DSurface",
    "xlAbove",
    "xlAccounting1",
    "xlAccounting2",
    "xlAccounting3",
    "xlAccounting4",
    "xlAdd",
    "xlAll",
    "xlAllExceptBorders",
    "xlAutomatic",
    "xlBar",
    "xlBelow",
    "xlBidi",
    "xlBidiCalendar",
    "xlBoth",
    "xlBottom",
    "xlCascade",
    "xlCenter",
    "xlCenterAcrossSelection",
    "xlChart4",
    "xlChartSeries",
    "xlChartShort",
    "xlChartTitles",
    "xlChecker",
    "xlCircle",
    "xlClassic1",
    "xlClassic2",
    "xlClassic3",
    "xlClosed",
    "xlColor1",
    "xlColor2",
    "xlColor3",
    "xlColumn",
    "xlCombination",
    "xlComplete",
    "xlConstants",
    "xlContents",
    "xlContext",
    "xlCorner",
    "xlCrissCross",
    "xlCross",
    "xlCustom",
    "xlDebugCodePane",
    "xlDefaultAutoFormat",
    "xlDesktop",
    "xlDiamond",
    "xlDirect",
    "xlDistributed",
    "xlDivide",
    "xlDoubleAccounting",
    "xlDoubleClosed",
    "xlDoubleOpen",
    "xlDoubleQuote",
    "xlDrawingObject",
    "xlEntireChart",
    "xlExcelMenus",
    "xlExtended",
    "xlFill",
    "xlFirst",
    "xlFixedValue",
    "xlFloating",
    "xlFormats",
    "xlFormula",
    "xlFullScript",
    "xlGeneral",
    "xlGray16",
    "xlGray25",
    "xlGray50",
    "xlGray75",
    "xlGray8",
    "xlGregorian",
    "xlGrid",
    "xlGridline",
    "xlHigh",
    "xlHindiNumerals",
    "xlIcons",
    "xlImmediatePane",
    "xlInside",
    "xlInteger",
    "xlJustify",
    "xlLast",
    "xlLastCell",
    "xlLatin",
    "xlLeft",
    "xlLeftToRight",
    "xlLightDown",
    "xlLightHorizontal",
    "xlLightUp",
    "xlLightVertical",
    "xlList1",
    "xlList2",
    "xlList3",
    "xlLocalFormat1",
    "xlLocalFormat2",
    "xlLogicalCursor",
    "xlLong",
    "xlLotusHelp",
    "xlLow",
    "xlLTR",
    "xlMacrosheetCell",
    "xlManual",
    "xlMaximum",
    "xlMinimum",
    "xlMinusValues",
    "xlMixed",
    "xlMixedAuthorizedScript",
    "xlMixedScript",
    "xlModule",
    "xlMultiply",
    "xlNarrow",
    "xlNextToAxis",
    "xlNoDocuments",
    "xlNone",
    "xlNotes",
    "xlOff",
    "xlOn",
    "xlOpaque",
    "xlOpen",
    "xlOutside",
    "xlPartial",
    "xlPartialScript",
    "xlPercent",
    "xlPlus",
    "xlPlusValues",
    "xlReference",
    "xlRight",
    "xlRTL",
    "xlScale",
    "xlSemiautomatic",
    "xlSemiGray75",
    "xlShort",
    "xlShowLabel",
    "xlShowLabelAndPercent",
    "xlShowPercent",
    "xlShowValue",
    "xlSimple",
    "xlSingle",
    "xlSingleAccounting",
    "xlSingleQuote",
    "xlSolid",
    "xlSquare",
    "xlStar",
    "xlStError",
    "xlStrict",
    "xlSubtract",
    "xlSystem",
    "xlTextBox",
    "xlTiled",
    "xlTitleBar",
    "xlToolbar",
    "xlToolbarButton",
    "xlTop",
    // xlTopToBottom — already listed in XlSortOrientation above
    "xlTransparent",
    "xlTriangle",
    "xlVeryHidden",
    "xlVisible",
    "xlVisualCursor",
    "xlWatchPane",
    "xlWide",
    "xlWorkbookTab",
    "xlWorksheet4",
    "xlWorksheetCell",
    "xlWorksheetShort",
];
